mysql:
  enabled: false
  pool-size: 10
  host: 127.0.0.1
  port: 3306
  database: npcminigame
  table_prefix: "npcm_"
  username: root
  password: ""

npcs:
  '1':
    # This is the name of the NPC
    name: "npc1"
    # This is the skin. You can get these values from https://mineskin.org/
    texture: "ewogICJ0aW1lc3RhbXAiIDogMTYyNjQ3ODQ5OTg2MSwKICAicHJvZmlsZUlkIiA6ICJlZDUzZGQ4MTRmOWQ0YTNjYjRlYjY1MWRjYmE3N2U2NiIsCiAgInByb2ZpbGVOYW1lIiA6ICI0MTQxNDE0MWgiLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjgzZDBjOTIzMjliNGVlNDMyZmQzYzgwNWJiYjQ0YWI2ZWFlN2IxN2M3OTQ1ZDMyNzRiODMxNmI5YzA4Y2FhYSIsCiAgICAgICJtZXRhZGF0YSIgOiB7CiAgICAgICAgIm1vZGVsIiA6ICJzbGltIgogICAgICB9CiAgICB9CiAgfQp9"
    signature: "I+TLbStFtAG96DIyk7gbZab80LAcVwnfbPs0FeMQ7ShzBXlqkdfiHGqq839/Ix3FQSj1M7EpN6tC4xsZrWsKSmDXI9jtH/pyQ/Uex7g2cpVe9PHFcxK1wuuAA7ucsSao7F4EhBHc1MH6JfhMoSaiL9kAiazC8xdtcG0WKa/qZf2MKHA48aGMfAcZehK/Su0B1iVRv35LwUipgFasMqbcuqU9108O1QWM0P6I6H8qTZITfc5tYbsNfUHvYJmNT3tvyuT/29NOg6s9HvrsiTeiCv5GbEllQbb4v8d2K2X59kQ7eKlCSMqlAnokn8Qle3l9aNoIaWPkEpNRPrfDFHksZAMMOQx2tgYa4LglsjfdyOHvUUrx2Ma+NsZqLTjtKxys0hdr7rDg2GMRx1ZRqDtwg6bmySoA/m9KUl6Jgi6KKwZK9ckGAUAJRsbjBoOHg6y56CfIaTFFW2JWxfXAvYGygk7fWSCgKgMMVv3zwLhmT3UgRLh6CN8MSI+6rJPYOIx3pytt/4JcSqXO9/WDsup9khVLJF3M5tDB/Rg8hN+gsHu+viLrUt02J7fVkY/PObwpycxdiTG6q6Bk4aWIQsqcN++y7al+dPrbeXS+qe6vv9/Gdw++PTZMFJmPsMlubnk2Mq/E+WDYxe7Hey1/T2aodJwwIpYa1+PtCRLyh/kTW6A="
  '2':
    name: "npc2"
    texture: "ewogICJ0aW1lc3RhbXAiIDogMTYyNjQ3ODA4ODc0MywKICAicHJvZmlsZUlkIiA6ICJiYzRlZGZiNWYzNmM0OGE3YWM5ZjFhMzlkYzIzZjRmOCIsCiAgInByb2ZpbGVOYW1lIiA6ICI4YWNhNjgwYjIyNDYxMzQwIiwKICAic2lnbmF0dXJlUmVxdWlyZWQiIDogdHJ1ZSwKICAidGV4dHVyZXMiIDogewogICAgIlNLSU4iIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2IwMGY1OWZmMWMzYTljZmUzYzJhZDlhZjlhMTI2NmQyNzQ0MGQwNjI0N2UyZTY1Y2MyZjkyMDVmNjUxYjQ4ZGQiLAogICAgICAibWV0YWRhdGEiIDogewogICAgICAgICJtb2RlbCIgOiAic2xpbSIKICAgICAgfQogICAgfQogIH0KfQ=="
    signature: "VKOulS25KF++ks5LRXBINV2hRR1A2MN3INOppZOwX0moafYRkmppMxAmV1EVNlahOUR/61UpLITclQ3/mlIPDIyMJMBnrkr7fdsVwmdoTnP8dNr2sCWEzbe3dEjzygqw8MkRorWtKHHyd+BIp1+Ui/1Dxz4wpNC6JFKWGFa664pg8hIpYb0S63yI0nttRAxsVJDvwg789qR15Q1a8PGn1dfMpo3yFNpp3Qo4BKKQIXnQJ5JAEgVf6heUNrOZOiTu8HoMpFDbEH+PzERss2O0HxbmnYorIMMME/5rDpNexSLfEg3Fn6A0nS5BpzWblYE2V5v1WMiXg+x9Lfo0mFcIu/uQH7zblOGQxU+PDeSwEymsR+4N7lmopIZE81T9rzekbiwGfVnmoIlM1J1ko7bRtIOUS921UIYIz9mzLcTqx0e9QzdGOYvQMZ0JR4HN+c9nxAQD/QFF0DysJsHMKPH7nUYdH6xcpbp9+v2YlEUF1F0a1OYYUShPWIc02Qvd540wp0qjVdZFVBoGMkTHUJ7ShdxZyh4FhO8k4+9D/vo4LXwUBTw7/Ak7DtVMT33DImCbR2LYCr9SHY72qpp8fPePvIv0PdiV3rEZGL5Pm38OnVFjNCO2k8A8eyeXicxE8rwCrBacEataZj2/dm+zGcg79+koldrQldusFBYO6fqwwAM="
  '3':
    name: "npc2"
    texture: "ewogICJ0aW1lc3RhbXAiIDogMTYyNjQ3ODAzNDc0MiwKICAicHJvZmlsZUlkIiA6ICIwNWJhN2FmOGY0M2M0NGFjYWJkZjkzZjVmMTk2Njg3NiIsCiAgInByb2ZpbGVOYW1lIiA6ICJESkdyb3VuZDAiLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZThhOWMwZThiNjU5MWY3MWVlYzczMWEyZDdkODJlY2I0NmMwYjRmYzg4Y2IxNGIxOTE1Yjc2YTNhOTUwZjk2OCIsCiAgICAgICJtZXRhZGF0YSIgOiB7CiAgICAgICAgIm1vZGVsIiA6ICJzbGltIgogICAgICB9CiAgICB9CiAgfQp9"
    signature: "bQtD+sRNP60ODWF0A4jaaLtTGk2DC7pCHNX6mWADV9PB5S4yHCxkYt41gPX44ZQyZSVFLlyHYGeBBp9skRBK5EWKrlSe+jJ2EUbKmV5JkbOeoaDvi6HJ/w/gBLVkvD9t6egNJeHxQ7nMRluGCCK4Gd90dfXLCEyOjcQziTDJknKyP8aWJfdvdupXLAr3ih7G9o+oSCqp2tTYbu1IJjzui/CjctXS8mAEnPcWatmP5Of19GwPvoWsFdAeVcxkMSkrKll5R+vP9UKqyzRFD91LViApmo0qmjSWXqIcCzzHYsG5dr1JPAtdltkXrLC/TdOwY2cs+Had/qrt5uLTxCIBV2sD0w0C92zqqbsrSyQOVg0U+cMrJRf03hnESXPKR5SMFlv/k3yC7R1bDGqiiUwhdUNRHi+wh53LBNvqJv3/GIBrZUjZPgmC8YjdApINi4MkUe4mOesfjx+16JNjcqbvwetrYAp5tAbVr1fFx2cFtS6QdmBL498Mj+cuxIK7Bu80rrtOJdY6VBlKYFERb+FiPEhPiCbKEYP4jkHOISGO7WD76T336xvHXVr/Y7PMbD11d1RX3mYVTpe79FpWGqY1Og/cukns+aYlCQ2z77b+hh7xAkd7AWNRfXFXwEGU1kj1x7W27Qe/nKLIFHmUcfu96eIK7V/IgZkSzTsM6zmuXlg="

# Countdown for the game to start
countdown: 15
# Retries to check if the location is valid for the NPC. Default: 100
retries: 100
# The time the game will run for
max_time_to_find_npc: 360
# The level of the speed given to the players when a game is running
level_of_speed: 2

# Settings for the random spawn for the NPC
random_settings:
  # Y level the NPC can spawn on
  y_level: 70
  # Radius to check validity of the randomness
  radius: 10

winner_commands:
  - "/say %player% won. You can change this on the config."

message:
  npc_start_countdown: "&7Starting in: &b%time%s"
  npc_start_title:
    title: "&a&lNPC HIDDEN"
    subtitle: "&aMinigame started"
  npc_hint: "&aThe NPC %name% hid in the biome %biome%"
  winner_title:
    title: "&7Congratulations"
    subtitle: "&8You won!"
  winner_message: "&7The user %player% won the minigame. Thank you for playing :D"
  timeout_message: "&cThe time ran, and no one found the NPC. Better luck next time!"