name: NPCFindMinigame
version: @version@
main: com.dolphln.npcfindminigame.NPCFindMinigame
api-version: 1.16
authors: [ Dolphln ]
description: NPCFindMinigame
website: dolphln.com

depend:
  - ProtocolLib
softdepend:
  - PlaceholderAPI
